name: CD

on:
  push:
      branches: [ master ]

jobs:
    deploy:
          runs-on: ubuntu-latest
          steps:
              -   uses: actions/checkout@v2
              -   name: Deploy to production
                  uses: appleboy/ssh-action@master
                  with:
                      host: ${{ secrets.SSH_HOST }}
                      username: ${{ secrets.SSH_USERNAME }}
                      password: ${{ secrets.SSH_PASSWORD }}
                      script: |
                        whoami
                        cd ./public_html/test.nikahhelp.com
                        ls
                        git clone github.com/Ru1n00/test.git
